kind: pipeline
name: Surya_bleed

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&bleed
    image: ubuntu:latest
    environment:
      BOTTOKEN:
        from_secret: token
      CHATID:
        from_secret: chat_id
    commands:
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio
      - mkdir kernul && cd kernul
      - wget https://raw.githubusercontent.com/lybdroid/kernel_xiaomi_surya_stormbreaker/alpha-new/.circleci/bleed.sh
      - chmod +x bleed.sh
      - bash bleed.sh

